# -*- coding: utf-8 -*-
"""OBELIX_DOS_PDOS_Association_Onecell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tSZ6AuyJvso6vlD5XRXwB0jGlAWbZw1
"""

# ================================================================
# OBELiX total phonon DOS + Li-projected DOS association workflow
# Single-cell Google Colab script
# ================================================================

# ------------------------- USER CONFIGURATION -------------------------
# ---------------------- GOOGLE DRIVE CONFIGURATION ----------------------
# Before running:
# Google Drive -> Shared with me -> right-click "PDOS and DOS"
# -> Organize -> Add shortcut -> My Drive

MOUNT_POINT = "/content/drive"
MYDRIVE_ROOT = "/content/drive/MyDrive"

# Path to the shortcut created in My Drive.
# Change this only if you placed the shortcut inside another My Drive folder.
PDOS_DOS_DRIVE_FOLDER = "/content/drive/.shortcut-targets-by-id/1DjYaQ_hrY0kk_XPL7NMYO_wrYqOPoAxv"

AUTO_DOWNLOAD_ZIP = True
WORKDIR = "/content/obelix_dos_pdos_association"
FORCE_REDOWNLOAD = False
AUTO_DOWNLOAD_ZIP = True

# Frequency preprocessing: every structure is retained if it has readable data
# in this interval. Negative-frequency points are recorded but never used to
# reject a structure.
FREQ_MIN_THz = 0.0               # strict condition is frequency > 0
FREQ_MAX_THz = 100.0             # frequency <= 100 THz
FREQUENCY_SCALE_TO_THz = 1.0     # leave at 1.0 for Phonopy's usual THz output
BIN_WIDTHS_THz = (0.5, 1.0, 2.0)
PRIMARY_BIN_WIDTH_THz = 1.0

# Conductivity values reported as upper limits, e.g. <1E-10, are treated at
# their reporting limit in the primary analysis. Two sensitivity analyses are
# also exported: half-limit substitution and exclusion of censored values.
PRIMARY_CENSOR_POLICY = "limit"  # "limit", "half_limit", or "exclude"

# Statistical settings. Raise these for final publication runs.
RANDOM_SEED = 42
N_BOOTSTRAP = 500
N_PERMUTATIONS = 1000
N_MI_PERMUTATIONS = 100
PERMUTATION_BATCH_SIZE = 128
FDR_ALPHA = 0.05
RUN_SPLINE_NONLINEARITY = True
RUN_CONDITIONAL_ASSOCIATIONS = True
RUN_PREDICTIVE_MODELS = True
RUN_XGBOOST = True

# PDOS parsing fallback. The official Phonopy projected_dos.dat contains one
# column per atom (or 3 columns per atom for XYZ projection). The code first
# searches nearby phonopy YAML/POSCAR/CIF metadata to identify Li columns.
# Because the supplied Drive folders are stated to contain Li-projected DOS,
# a metadata-free multi-column file is summed as a last resort and prominently
# flagged in QC. Set to "error" to forbid that fallback.
PDOS_MULTICOLUMN_FALLBACK = "error"  # or "error"
TOTAL_DOS_COLUMN = 1                         # one-based among DOS columns after frequency

# ------------------------- PACKAGE INSTALLATION -------------------------
import sys, subprocess, os
required = [
    "pymatgen>=2024.5.1",
    "dcor>=0.6",
    "statsmodels>=0.14",
    "xgboost>=2.0",
    "pyyaml>=6.0",
]
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *required])

# ------------------------------- IMPORTS -------------------------------
import re, json, math, shutil, warnings, traceback, zipfile, tarfile
from pathlib import Path
from collections import defaultdict
import numpy as np
import pandas as pd
import yaml
import matplotlib.pyplot as plt
from scipy import stats
from scipy.integrate import cumulative_trapezoid
from scipy.stats import rankdata
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold, KFold, GridSearchCV, cross_val_predict
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, SplineTransformer
from sklearn.feature_selection import mutual_info_regression
from statsmodels.stats.multitest import multipletests
import dcor
from pymatgen.core import Composition, Element, Structure

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
np.random.seed(RANDOM_SEED)

try:
    import torch
    GPU_AVAILABLE = bool(torch.cuda.is_available())
    DEVICE_NAME = torch.cuda.get_device_name(0) if GPU_AVAILABLE else "CPU"
except Exception:
    torch = None
    GPU_AVAILABLE = False
    DEVICE_NAME = "CPU"

print(f"Compute device detected: {DEVICE_NAME}")
print("GPU acceleration is used for permutation tests and XGBoost when CUDA is available.")

# ----------------------------- DIRECTORIES -----------------------------
ROOT = Path(WORKDIR)
DOWNLOAD_ROOT = ROOT / "downloads"
RESULTS = ROOT / "results"
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
FEATURES_DIR = RESULTS / "features"
ASSOC_DIR = RESULTS / "associations"
for p in [DOWNLOAD_ROOT, RESULTS, FIGURES, TABLES, FEATURES_DIR, ASSOC_DIR]:
    p.mkdir(parents=True, exist_ok=True)

# -------------------- MOUNT AND RESOLVE DRIVE DATA --------------------
from google.colab import drive
from pathlib import Path
import os

MOUNT_POINT = "/content/drive"
drive.mount(MOUNT_POINT, force_remount=True)

# ----------------------------------------------------------------------
# Your current Google Drive folders.
# Each material subfolder, e.g. 122/, aab/, 6ji/, contains BOTH:
#   Lithium_PDOS_<material_id>.csv
#   Total_DOS_<material_id>.csv
# ----------------------------------------------------------------------
TRAIN_ROOT = Path("/content/drive/.shortcut-targets-by-id/1_rZkiXnggqDBzgsITf1d7V4K_4aJ00gF")
TEST_ROOT  = Path("/content/drive/.shortcut-targets-by-id/1uDZz5V21SkVn1nYYRn2QD8YrBPfGKoF1")

# If direct folder-ID paths do not work in your Colab session, comment the two
# lines above and uncomment these two MyDrive paths instead:
# TRAIN_ROOT = Path("/content/drive/MyDrive/Train_cif_dos_code-2")
# TEST_ROOT  = Path("/content/drive/MyDrive/Test_cif_dos_code-2")


def usable_directory(path):
    """True when Drive exposes path as a readable directory."""
    try:
        return path.exists() and path.is_dir() and os.access(path, os.R_OK)
    except Exception:
        return False


def show_directory(path, max_entries=100):
    print(f"\nContents of: {path}")
    if not usable_directory(path):
        print("  [not accessible]")
        return

    try:
        entries = sorted(path.iterdir(), key=lambda p: p.name.lower())
        for p in entries[:max_entries]:
            kind = "DIR " if p.is_dir() else "FILE"
            print(f"  {kind}  {repr(p.name)}")
        if len(entries) > max_entries:
            print(f"  ... and {len(entries) - max_entries} more entries")
    except Exception as exc:
        print(f"  Could not list directory: {exc}")


def check_folder(root, label):
    if not usable_directory(root):
        print("\nTop-level MyDrive folders:")
        show_directory(Path(MOUNT_POINT) / "MyDrive", max_entries=100)

        print("\nVisible shortcut-target IDs:")
        show_directory(Path(MOUNT_POINT) / ".shortcut-targets-by-id", max_entries=100)

        raise FileNotFoundError(
            f"{label} folder not found or not readable:\n{root}\n\n"
            "If this is a shared folder, add a shortcut to My Drive or run Colab "
            "with the Google account that has access."
        )

    li_files = sorted(root.rglob("Lithium_PDOS_*.csv"))
    total_files = sorted(root.rglob("Total_DOS_*.csv"))

    print(f"{label}: {root}")
    print(f"  Li PDOS files: {len(li_files)}")
    print(f"  Total DOS files: {len(total_files)}")

    if len(li_files) == 0:
        raise RuntimeError(f"No Lithium_PDOS_*.csv files found in {root}")
    if len(total_files) == 0:
        raise RuntimeError(f"No Total_DOS_*.csv files found in {root}")


check_folder(TRAIN_ROOT, "TRAIN")
check_folder(TEST_ROOT, "TEST")

# Your new folders contain both Li-PDOS and Total-DOS files, so PDOS and DOS
# roots are the same for each split.
TRAIN_PDOS_ROOT = TRAIN_ROOT
TRAIN_DOS_ROOT = TRAIN_ROOT
TEST_PDOS_ROOT = TEST_ROOT
TEST_DOS_ROOT = TEST_ROOT

FOLDER_SPECS = {
    ("train", "pdos"): (None, TRAIN_PDOS_ROOT),
    ("train", "dos"):  (None, TRAIN_DOS_ROOT),
    ("test",  "pdos"): (None, TEST_PDOS_ROOT),
    ("test",  "dos"):  (None, TEST_DOS_ROOT),
}

print("\nResolved dataset folders")
print("-" * 80)
for (split, mode), (_, root) in FOLDER_SPECS.items():
    file_count = sum(1 for p in root.rglob("*") if p.is_file())
    print(
        f"{split.upper():5s} {mode.upper():4s}: "
        f"{file_count:,} files\n"
        f"  {root}"
    )

print("\nAll folders are accessible. No files will be downloaded.")
# --------------------------- HELPER FUNCTIONS --------------------------
def folder_has_files(path: Path) -> bool:
    return path.exists() and any(p.is_file() for p in path.rglob("*"))


def download_public_folder(url: str, destination: Path):
    if FORCE_REDOWNLOAD and destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    if folder_has_files(destination):
        print(f"Using existing download: {destination}")
        return
    print(f"Downloading public Drive folder into: {destination}")
    try:
        gdown.download_folder(url=url, output=str(destination), quiet=False, use_cookies=False)
    except Exception as exc:
        raise RuntimeError(
            f"Could not download {url}. Verify that every item is shared as "
            "'Anyone with the link — Viewer'. Original error: {exc}"
        ) from exc
    if not folder_has_files(destination):
        raise RuntimeError(f"No files were downloaded from {url}")


def extract_archives_recursively(root: Path):
    """Extract archives found in downloaded folders; harmless if none exist."""
    archives = [p for p in root.rglob("*") if p.is_file() and (
        p.suffix.lower() == ".zip" or p.name.lower().endswith((".tar.gz", ".tgz", ".tar"))
    )]
    for arc in archives:
        out = arc.parent / f"{arc.stem}_extracted"
        marker = out / ".extracted_ok"
        if marker.exists():
            continue
        out.mkdir(parents=True, exist_ok=True)
        try:
            shutil.unpack_archive(str(arc), str(out))
            marker.touch()
            print(f"Extracted archive: {arc.name}")
        except Exception as exc:
            print(f"WARNING: could not extract {arc}: {exc}")


def normalize_id(x):
    return str(x).strip().lower()


def parse_conductivity(value):
    """Return (reported numeric limit/value, censor flag, comparator)."""
    if pd.isna(value):
        return np.nan, False, ""
    s = str(value).strip().replace("−", "-").replace("×", "x")
    comparator = "<" if "<" in s else (">" if ">" in s else "")
    # Handles forms such as 1E-10, 1e-10, and 1 x 10^-10.
    s2 = re.sub(r"([0-9.]+)\s*[xX]\s*10\s*\^?\s*([-+]?\d+)", r"\1e\2", s)
    match = re.search(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?", s2)
    if not match:
        return np.nan, False, comparator
    try:
        val = float(match.group(0))
    except Exception:
        return np.nan, False, comparator
    return val, comparator == "<", comparator


def prepare_obelix(df: pd.DataFrame, split: str) -> pd.DataFrame:
    df = df.copy()
    df["ID"] = df["ID"].map(normalize_id)
    parsed = df["Ionic conductivity (S cm-1)"].map(parse_conductivity)
    df["ic_reported"] = [x[0] for x in parsed]
    df["ic_is_upper_limit"] = [x[1] for x in parsed]
    df["ic_comparator"] = [x[2] for x in parsed]
    df.loc[df["ic_reported"] <= 0, "ic_reported"] = np.nan
    df["ic_limit"] = df["ic_reported"]
    df["ic_half_limit"] = np.where(df["ic_is_upper_limit"], 0.5 * df["ic_reported"], df["ic_reported"])
    df["ic_exclude"] = np.where(df["ic_is_upper_limit"], np.nan, df["ic_reported"])
    for policy in ["limit", "half_limit", "exclude"]:
        df[f"log10_ic_{policy}"] = np.log10(df[f"ic_{policy}"].astype(float))
    df["split"] = split
    return df


def target_column(policy: str) -> str:
    if policy not in {"limit", "half_limit", "exclude"}:
        raise ValueError(f"Unknown censor policy: {policy}")
    return f"log10_ic_{policy}"


def safe_numeric_table(path: Path):
    """Read a whitespace/comma/tab/semicolon numeric table robustly."""
    best = None
    for delim in [None, ",", "\t", ";"]:
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                arr = np.genfromtxt(path, comments="#", delimiter=delim, invalid_raise=False, dtype=float)
            if arr.ndim == 1:
                arr = arr.reshape(1, -1)
            if arr.ndim != 2:
                continue
            arr = arr[:, ~np.all(~np.isfinite(arr), axis=0)]
            if arr.shape[1] < 2:
                continue
            arr = arr[np.isfinite(arr[:, 0])]
            if len(arr) >= 2 and (best is None or arr.shape[1] > best.shape[1]):
                best = arr
        except Exception:
            pass
    if best is None:
        raise ValueError("No readable numeric table with >=2 columns")
    return best


def collect_symbol_lists(obj, path="root"):
    found = []
    if isinstance(obj, dict):
        for key, val in obj.items():
            new_path = f"{path}/{key}"
            if key in {"points", "atoms"} and isinstance(val, list) and val:
                symbols = []
                ok = True
                for item in val:
                    if not isinstance(item, dict):
                        ok = False; break
                    sym = item.get("symbol", item.get("element", item.get("name")))
                    if sym is None:
                        ok = False; break
                    symbols.append(str(sym))
                if ok and symbols:
                    found.append((new_path, symbols))
            found.extend(collect_symbol_lists(val, new_path))
    elif isinstance(obj, list):
        for i, val in enumerate(obj):
            found.extend(collect_symbol_lists(val, f"{path}/{i}"))
    return found


def symbols_from_yaml(path: Path):
    try:
        with open(path, "r", errors="ignore") as f:
            data = yaml.safe_load(f)
        candidates = collect_symbol_lists(data)
        # Prefer primitive cell, then unit cell, then other lists.
        candidates.sort(key=lambda z: (0 if "primitive" in z[0].lower() else 1 if "unit" in z[0].lower() else 2, len(z[1])))
        return [(symbols, f"yaml:{path.name}:{where}") for where, symbols in candidates]
    except Exception:
        return []


def symbols_from_poscar(path: Path):
    try:
        lines = [x.strip() for x in path.read_text(errors="ignore").splitlines() if x.strip()]
        if len(lines) < 7:
            return []
        elem_tokens = lines[5].split()
        count_tokens = lines[6].split()
        if not elem_tokens or not count_tokens:
            return []
        if all(re.fullmatch(r"[A-Za-z]{1,3}", x) for x in elem_tokens) and all(re.fullmatch(r"\d+", x) for x in count_tokens):
            counts = [int(x) for x in count_tokens]
            if len(counts) == len(elem_tokens):
                symbols = [e for e, n in zip(elem_tokens, counts) for _ in range(n)]
                return [(symbols, f"poscar:{path.name}")]
    except Exception:
        pass
    return []


def symbols_from_structure(path: Path):
    try:
        structure = Structure.from_file(str(path))
        symbols = []
        for site in structure:
            # Mark a partially occupied site as Li when Li is one of its species.
            species_names = [el.symbol for el in site.species.elements]
            symbols.append("Li" if "Li" in species_names else species_names[0])
        return [(symbols, f"structure:{path.name}")]
    except Exception:
        return []


def nearby_metadata_candidates(data_path: Path, collection_root: Path):
    dirs = []
    d = data_path.parent
    collection_root = collection_root.resolve()
    while True:
        dirs.append(d)
        if d.resolve() == collection_root or d.parent == d:
            break
        try:
            if collection_root not in d.resolve().parents and d.resolve() != collection_root:
                break
        except Exception:
            break
        d = d.parent
    files = []
    for directory in dirs:
        for name in ["phonopy.yaml", "phonopy_disp.yaml", "phonopy_params.yaml", "PPOSCAR", "POSCAR", "CONTCAR"]:
            q = directory / name
            if q.exists() and q.is_file():
                files.append(q)
        files.extend(sorted(directory.glob("*.cif"))[:5])
    # preserve order while removing duplicates
    unique = []
    seen = set()
    for f in files:
        s = str(f.resolve())
        if s not in seen:
            unique.append(f); seen.add(s)
    return unique


def infer_symbols(data_path: Path, collection_root: Path, n_density_cols: int):
    all_candidates = []
    for meta in nearby_metadata_candidates(data_path, collection_root):
        lname = meta.name.lower()
        if lname.endswith((".yaml", ".yml")):
            all_candidates.extend(symbols_from_yaml(meta))
        elif lname in {"poscar", "contcar", "pposcar"}:
            all_candidates.extend(symbols_from_poscar(meta))
        elif lname.endswith(".cif"):
            all_candidates.extend(symbols_from_structure(meta))
    matching = []
    for symbols, source in all_candidates:
        if len(symbols) == n_density_cols:
            matching.append((0, symbols, source, "atom"))
        if 3 * len(symbols) == n_density_cols:
            matching.append((1, symbols, source, "xyz"))
    if not matching:
        return None, None, None
    matching.sort(key=lambda x: x[0])
    _, symbols, source, projection = matching[0]
    return symbols, source, projection


def select_density(arr: np.ndarray, path: Path, mode: str, collection_root: Path):
    freq = arr[:, 0].astype(float) * FREQUENCY_SCALE_TO_THz
    D = arr[:, 1:].astype(float)
    nden = D.shape[1]
    if mode == "dos":
        col = TOTAL_DOS_COLUMN - 1
        if col < 0 or col >= nden:
            raise ValueError(f"TOTAL_DOS_COLUMN={TOTAL_DOS_COLUMN} incompatible with {nden} density columns")
        dens = D[:, col]
        parse_mode = f"total_column_{TOTAL_DOS_COLUMN}"
        metadata_source = ""
    elif mode == "pdos":
        if nden == 1:
            dens = D[:, 0]
            parse_mode = "single_Li_PDOS_column"
            metadata_source = "not_needed"
        else:
            symbols, metadata_source, projection = infer_symbols(path, collection_root, nden)
            if symbols is not None:
                li_atoms = [i for i, s in enumerate(symbols) if str(s).strip().lower() == "li"]
                if not li_atoms:
                    raise ValueError(f"Metadata found but no Li atoms identified ({metadata_source})")
                if projection == "atom":
                    cols = li_atoms
                else:
                    cols = [3 * i + j for i in li_atoms for j in range(3)]
                dens = np.nansum(D[:, cols], axis=1)
                parse_mode = f"Li_columns_from_{projection}_resolved_PDOS"
            elif PDOS_MULTICOLUMN_FALLBACK == "sum_all_as_Li":
                dens = np.nansum(D, axis=1)
                parse_mode = "FALLBACK_sum_all_columns_as_Li"
                metadata_source = "NO_MATCHING_METADATA"
            else:
                raise ValueError(
                    f"PDOS has {nden} density columns but Li columns could not be identified. "
                    "Provide phonopy.yaml/POSCAR/CIF metadata or enable fallback."
                )
    else:
        raise ValueError(mode)
    return freq, dens, nden, parse_mode, metadata_source

def normalize_header_name(name):
    """Normalize a table header for robust matching."""
    return re.sub(r"[^a-z0-9]+", "", str(name).strip().lower())


def read_named_spectrum_table(path: Path, mode: str):
    """
    Read spectrum files containing explicit column headers.

    Expected preferred columns:
        Frequency_THz
        Total_DOS
        Li_PDOS

    For mode='dos', only Total_DOS is selected.
    For mode='pdos', only Li_PDOS is selected.

    Returns None when recognizable headers are not present, allowing the
    original Phonopy .dat parser to be used as a fallback.
    """
    try:
        # sep=None allows pandas to infer comma, tab, or whitespace separators.
        df = pd.read_csv(
            path,
            sep=None,
            engine="python",
            comment="#"
        )
    except Exception:
        return None

    if df is None or df.empty or len(df.columns) < 2:
        return None

    original_columns = list(df.columns)
    normalized = {
        col: normalize_header_name(col)
        for col in original_columns
    }

    # Identify frequency column.
    frequency_aliases = {
        "frequencythz",
        "frequency",
        "freqthz",
        "freq",
        "phononfrequencythz",
    }

    frequency_columns = [
        col for col, norm in normalized.items()
        if norm in frequency_aliases
    ]

    if not frequency_columns:
        return None

    frequency_column = frequency_columns[0]

    if mode == "dos":
        # Prefer exact Total_DOS.
        exact_columns = [
            col for col, norm in normalized.items()
            if norm == "totaldos"
        ]

        if exact_columns:
            selected_columns = [exact_columns[0]]
        else:
            selected_columns = [
                col for col, norm in normalized.items()
                if "total" in norm and "dos" in norm
            ]

        if not selected_columns:
            return None

        # A total DOS should be one explicitly named column.
        selected_columns = [selected_columns[0]]
        parse_mode = "named_column_Total_DOS"

    elif mode == "pdos":
        # Prefer exact Li_PDOS.
        exact_columns = [
            col for col, norm in normalized.items()
            if norm == "lipdos"
        ]

        if exact_columns:
            selected_columns = [exact_columns[0]]
            parse_mode = "named_column_Li_PDOS"

        else:
            # Support files with separate Li components, such as:
            # Li_PDOS_x, Li_PDOS_y, Li_PDOS_z
            # or Li1_PDOS, Li2_PDOS, etc.
            selected_columns = [
                col for col, norm in normalized.items()
                if (
                    norm.startswith("lipdos")
                    or (
                        "li" in norm
                        and (
                            "pdos" in norm
                            or "projecteddos" in norm
                        )
                    )
                )
                and "total" not in norm
            ]

            if not selected_columns:
                return None

            parse_mode = "summed_named_Li_PDOS_columns"

    else:
        raise ValueError(f"Unknown spectrum mode: {mode}")

    frequency = pd.to_numeric(
        df[frequency_column],
        errors="coerce"
    ).to_numpy(float)

    density_matrix = np.column_stack([
        pd.to_numeric(df[col], errors="coerce").to_numpy(float)
        for col in selected_columns
    ])

    # Sum only explicitly identified Li columns when there are multiple
    # Li atoms or Cartesian components.
    density = np.nansum(density_matrix, axis=1)

    metadata_source = (
        f"table_header;"
        f"frequency_column={frequency_column};"
        f"selected_density_columns={selected_columns}"
    )

    number_density_columns = len(original_columns) - 1

    return (
        frequency,
        density,
        number_density_columns,
        parse_mode,
        metadata_source,
    )
def preprocess_spectrum(path: Path, mode: str, collection_root: Path):
    """
    Read and preprocess one DOS or Li-PDOS spectrum.

    Priority:
      1. Use explicitly named columns such as Total_DOS and Li_PDOS.
      2. Fall back to the original numeric Phonopy parser only when named
         columns are not present.

    Structures with negative frequencies are retained. Only points satisfying

        0 < frequency <= 100 THz

    are used to construct spectral features.
    """

    # First try explicit header-based parsing.
    named_result = read_named_spectrum_table(path, mode)

    if named_result is not None:
        (
            freq,
            dens,
            nden,
            parse_mode,
            metadata_source,
        ) = named_result

    else:
        # Fall back to the original Phonopy-style numeric table parser.
        arr = safe_numeric_table(path)

        (
            freq,
            dens,
            nden,
            parse_mode,
            metadata_source,
        ) = select_density(
            arr,
            path,
            mode,
            collection_root
        )

    freq = np.asarray(freq, dtype=float)
    dens = np.asarray(dens, dtype=float)

    finite = np.isfinite(freq) & np.isfinite(dens)
    freq = freq[finite]
    dens = dens[finite]

    if len(freq) < 2:
        raise ValueError("Fewer than two finite frequency–density rows")

    order = np.argsort(freq)
    freq = freq[order]
    dens = dens[order]

    negative_intensity_points = int(np.sum(dens < 0))

    # Clip only negative DOS intensity values caused by numerical noise.
    dens = np.clip(dens, 0.0, None)

    # Average duplicate frequency rows rather than double-counting them.
    spectrum_df = pd.DataFrame({
        "frequency": freq,
        "density": dens,
    })

    spectrum_df = (
        spectrum_df
        .groupby("frequency", as_index=False)["density"]
        .mean()
    )

    freq = spectrum_df["frequency"].to_numpy(float)
    dens = spectrum_df["density"].to_numpy(float)

    # Negative-frequency information is diagnostic only.
    negative_mask = freq < 0

    negative_area = (
        float(np.trapezoid(
            dens[negative_mask],
            freq[negative_mask]
        ))
        if np.sum(negative_mask) >= 2
        else 0.0
    )

    # This is the only frequency-selection rule.
    # No structure is rejected merely because it contains negative modes.
    positive_mask = (
        (freq > FREQ_MIN_THz)
        & (freq <= FREQ_MAX_THz)
    )

    x = freq[positive_mask]
    y = dens[positive_mask]

    if len(x) < 2:
        raise ValueError(
            f"Fewer than two points satisfy "
            f"{FREQ_MIN_THz} < frequency <= {FREQ_MAX_THz} THz"
        )

    positive_area = float(np.trapezoid(y, x))

    if not np.isfinite(positive_area) or positive_area <= 0:
        raise ValueError(
            "Non-positive integrated spectral weight over the selected "
            "positive-frequency interval"
        )

    qc = {
        "file": str(path),
        "mode": mode,
        "parse_mode": parse_mode,
        "metadata_source": metadata_source,
        "numeric_rows": int(len(freq)),
        "density_columns_in_source": int(nden),
        "min_frequency_raw_THz": float(np.min(freq)),
        "max_frequency_raw_THz": float(np.max(freq)),
        "negative_frequency_points": int(np.sum(freq < 0)),
        "zero_frequency_points": int(np.sum(freq == 0)),
        "used_positive_frequency_points": int(len(x)),
        "negative_intensity_points_clipped": (
            negative_intensity_points
        ),
        "negative_frequency_area_diagnostic": negative_area,
        "positive_area_0_to_100_THz": positive_area,
    }

    return {
        "frequency": x,
        "density": y,
        "qc": qc,
    }

def extract_obelix_id(path: Path, collection_root: Path, known_ids: set):
    try:
        rel_parts = path.relative_to(collection_root).parts
    except Exception:
        rel_parts = path.parts
    # Prefer exact 3-character tokens, searching closest path components first.
    for part in reversed(rel_parts):
        stem = Path(part).stem.lower()
        tokens = re.findall(r"(?<![a-z0-9])([a-z0-9]{3})(?![a-z0-9])", stem)
        for token in tokens:
            if token in known_ids:
                return token
        if stem in known_ids:
            return stem
    # Then accept IDs at the beginning/end of a longer filename component.
    for part in reversed(rel_parts):
        stem = Path(part).stem.lower()
        for token in re.split(r"[^a-z0-9]+", stem):
            if token in known_ids:
                return token
        for oid in known_ids:
            if stem.startswith(oid + "_") or stem.startswith(oid + "-") or stem.endswith("_" + oid) or stem.endswith("-" + oid):
                return oid
    return None


def spectrum_file_score(path: Path, mode: str):
    name = path.name.lower()
    full = str(path).lower()
    score = 0
    if mode == "dos":
        if name == "total_dos.dat": score += 200
        if "total_dos" in name or "total-dos" in name: score += 160
        if "dos" in name: score += 50
        if "project" in name or "pdos" in name: score -= 150
    else:
        if "li" in name and ("pdos" in name or "project" in name): score += 230
        if name == "projected_dos.dat": score += 200
        if "projected_dos" in name or "projected-dos" in name: score += 170
        if "pdos" in name: score += 130
        if "dos" in name: score += 30
        if "total_dos" in name: score -= 200
    if path.suffix.lower() == ".dat": score += 10
    if any(x in full for x in ["figure", "plot", "image", "band", "dispersion"]): score -= 50
    return score


def index_spectrum_files(collection_root: Path, mode: str, known_ids: set):
    allowed_ext = {".dat", ".txt", ".csv", ".tsv"}
    candidates = defaultdict(list)
    unmatched = []
    for path in collection_root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in allowed_ext:
            continue
        score = spectrum_file_score(path, mode)
        if score <= 0:
            continue
        oid = extract_obelix_id(path, collection_root, known_ids)
        row = {"mode": mode, "file": str(path), "score": score, "matched_ID": oid or ""}
        if oid is None:
            unmatched.append(row)
        else:
            candidates[oid].append((score, -len(str(path)), path))
    selected = {}
    index_rows = []
    for oid, items in candidates.items():
        items.sort(reverse=True)
        selected[oid] = items[0][2]
        for rank, (score, _, path) in enumerate(items, start=1):
            index_rows.append({
                "ID": oid, "mode": mode, "selected": rank == 1,
                "candidate_rank": rank, "score": score, "file": str(path)
            })
    return selected, pd.DataFrame(index_rows), pd.DataFrame(unmatched)


def load_collection(collection_root: Path, split: str, mode: str, known_ids: set):
    selected, index_df, unmatched_df = index_spectrum_files(collection_root, mode, known_ids)
    spectra, qc_rows, errors = {}, [], []
    print(f"{split.upper()} {mode.upper()}: {len(selected)} candidate structures indexed")
    for oid, path in sorted(selected.items()):
        try:
            spec = preprocess_spectrum(path, mode, collection_root)
            spectra[oid] = spec
            qc_rows.append({"ID": oid, "split": split, **spec["qc"], "status": "ok", "error": ""})
        except Exception as exc:
            errors.append({"ID": oid, "split": split, "mode": mode, "file": str(path), "status": "failed", "error": str(exc)})
    qc_df = pd.DataFrame(qc_rows + errors)
    print(f"  parsed successfully: {len(spectra)}; failed: {len(errors)}")
    return spectra, qc_df, index_df, unmatched_df


def integrate_bins(x, y, edges):
    cum = np.concatenate([[0.0], cumulative_trapezoid(y, x)])
    cedge = np.interp(edges, x, cum, left=0.0, right=cum[-1])
    areas = np.diff(cedge)
    return np.clip(areas, 0.0, None)


def weighted_quantile_from_spectrum(x, y, q):
    cum = np.concatenate([[0.0], cumulative_trapezoid(y, x)])
    if cum[-1] <= 0:
        return np.nan
    return float(np.interp(q * cum[-1], cum, x))


def spectral_descriptors(spec, prefix, entropy_edges):
    x, y = spec["frequency"], spec["density"]
    area = float(np.trapezoid(y, x))
    centroid = float(np.trapezoid(x * y, x) / area)
    variance = float(np.trapezoid(((x - centroid) ** 2) * y, x) / area)
    bins = integrate_bins(x, y, entropy_edges)
    p = bins / bins.sum() if bins.sum() > 0 else np.zeros_like(bins)
    nz = p[p > 0]
    entropy = float(-np.sum(nz * np.log(nz)) / np.log(len(p))) if len(nz) and len(p) > 1 else np.nan
    cum = np.concatenate([[0.0], cumulative_trapezoid(y, x)])
    def frac_below(th):
        return float(np.interp(th, x, cum, left=0.0, right=cum[-1]) / area)
    q05 = weighted_quantile_from_spectrum(x, y, 0.05)
    q50 = weighted_quantile_from_spectrum(x, y, 0.50)
    q95 = weighted_quantile_from_spectrum(x, y, 0.95)
    return {
        f"{prefix}_positive_area": area,
        f"{prefix}_centroid_THz": centroid,
        f"{prefix}_std_THz": math.sqrt(max(variance, 0.0)),
        f"{prefix}_median_THz": q50,
        f"{prefix}_q05_THz": q05,
        f"{prefix}_q95_THz": q95,
        f"{prefix}_bandwidth90_THz": q95 - q05,
        f"{prefix}_peak_THz": float(x[np.argmax(y)]),
        f"{prefix}_spectral_entropy": entropy,
        **{f"{prefix}_fraction_below_{th:g}THz": frac_below(th) for th in [2, 5, 10, 20]},
    }


def collection_to_features(spectra: dict, prefix: str, bin_width: float):
    edges = np.arange(FREQ_MIN_THz, FREQ_MAX_THz + 0.5 * bin_width, bin_width)
    if edges[-1] < FREQ_MAX_THz:
        edges = np.append(edges, FREQ_MAX_THz)
    rows_area, rows_shape = {}, {}
    labels = [f"{prefix}_{edges[i]:06.2f}_{edges[i+1]:06.2f}THz" for i in range(len(edges) - 1)]
    for oid, spec in spectra.items():
        area = integrate_bins(spec["frequency"], spec["density"], edges)
        rows_area[oid] = area
        rows_shape[oid] = area / area.sum() if area.sum() > 0 else np.full_like(area, np.nan)
    area_df = pd.DataFrame.from_dict(rows_area, orient="index", columns=labels)
    shape_df = pd.DataFrame.from_dict(rows_shape, orient="index", columns=labels)
    area_df.index.name = "ID"; shape_df.index.name = "ID"
    return area_df.sort_index(), shape_df.sort_index(), edges


def descriptors_table(spectra: dict, prefix: str):
    entropy_edges = np.arange(FREQ_MIN_THz, FREQ_MAX_THz + PRIMARY_BIN_WIDTH_THz, PRIMARY_BIN_WIDTH_THz)
    rows = {oid: spectral_descriptors(spec, prefix, entropy_edges) for oid, spec in spectra.items()}
    df = pd.DataFrame.from_dict(rows, orient="index").sort_index()
    df.index.name = "ID"
    return df


def corr_columns(X, y):
    X = np.asarray(X, float); y = np.asarray(y, float)
    Xc = X - np.mean(X, axis=0, keepdims=True)
    yc = y - np.mean(y)
    denom = np.sqrt(np.sum(Xc * Xc, axis=0) * np.sum(yc * yc))
    return np.divide(np.sum(Xc * yc[:, None], axis=0), denom, out=np.zeros(X.shape[1]), where=denom > 0)


def analytic_corr_p(r, n):
    r = np.clip(np.asarray(r), -0.999999999, 0.999999999)
    t = np.abs(r) * np.sqrt(max(n - 2, 1) / np.maximum(1.0 - r * r, 1e-15))
    return 2.0 * stats.t.sf(t, df=max(n - 2, 1))


def permutation_pvalues(X, y, observed, n_perm, seed, use_gpu=True):
    """Featurewise and max-|stat| permutation p-values for correlations."""
    rng = np.random.default_rng(seed)
    X = np.asarray(X, np.float32)
    y = np.asarray(y, np.float32)
    n, p = X.shape
    obs = np.abs(np.asarray(observed, float))
    counts = np.zeros(p, dtype=np.int64)
    maxstats = []

    if use_gpu and GPU_AVAILABLE and torch is not None:
        device = torch.device("cuda")
        Xt = torch.as_tensor(X, device=device)
        yt = torch.as_tensor(y, device=device)
        Xz = (Xt - Xt.mean(0)) / torch.clamp(Xt.std(0, unbiased=True), min=1e-12)
        Xz = torch.nan_to_num(Xz)
        done = 0
        gen = torch.Generator(device=device)
        gen.manual_seed(seed)
        while done < n_perm:
            b = min(PERMUTATION_BATCH_SIZE, n_perm - done)
            # Independent random permutations generated by sorting random keys.
            perm_idx = torch.argsort(torch.rand((n, b), device=device, generator=gen), dim=0)
            Yp = yt[perm_idx]
            Yz = (Yp - Yp.mean(0)) / torch.clamp(Yp.std(0, unbiased=True), min=1e-12)
            R = (Xz.T @ Yz) / max(n - 1, 1)  # p x b
            A = torch.abs(R)
            counts += torch.sum(A >= torch.as_tensor(obs[:, None], device=device), dim=1).cpu().numpy()
            maxstats.extend(torch.max(A, dim=0).values.cpu().numpy().tolist())
            done += b
        del Xt, yt, Xz
        torch.cuda.empty_cache()
    else:
        for _ in range(n_perm):
            rp = np.abs(corr_columns(X, y[rng.permutation(n)]))
            counts += rp >= obs
            maxstats.append(float(np.max(rp)))

    maxstats = np.asarray(maxstats)
    p_feature = (counts + 1) / (n_perm + 1)
    p_maxT = (np.sum(maxstats[:, None] >= obs[None, :], axis=0) + 1) / (n_perm + 1)
    return p_feature, p_maxT


def bootstrap_correlation_ci(X, y, spearman=False, n_boot=500, seed=42):
    rng = np.random.default_rng(seed)
    X0 = np.asarray(X, float)
    y0 = np.asarray(y, float)
    if spearman:
        # Rank-score bootstrap: efficient and stable for the large bin scan.
        X0 = np.apply_along_axis(rankdata, 0, X0)
        y0 = rankdata(y0)
    vals = np.empty((n_boot, X0.shape[1]), dtype=np.float32)
    n = len(y0)
    for b in range(n_boot):
        idx = rng.integers(0, n, n)
        vals[b] = corr_columns(X0[idx], y0[idx])
    return np.nanpercentile(vals, 2.5, axis=0), np.nanpercentile(vals, 97.5, axis=0)


def parse_bin_from_feature(name):
    m = re.search(r"_(\d+\.\d+)_(\d+\.\d+)THz$", str(name))
    if not m:
        return np.nan, np.nan, np.nan
    lo, hi = float(m.group(1)), float(m.group(2))
    return lo, hi, 0.5 * (lo + hi)


def make_cv_splits(n, groups=None, n_splits=5):
    if groups is not None:
        groups = np.asarray(groups)
        nunique = len(np.unique(groups))
        if nunique >= 3:
            gkf = GroupKFold(n_splits=min(n_splits, nunique))
            return list(gkf.split(np.arange(n), groups=groups))
    kf = KFold(n_splits=min(n_splits, max(2, n // 10)), shuffle=True, random_state=RANDOM_SEED)
    return list(kf.split(np.arange(n)))


def spline_cv_gain(X, y, groups=None):
    splits = make_cv_splits(len(y), groups=groups, n_splits=5)
    gains, lin_r2s, spline_r2s = [], [], []
    for j in range(X.shape[1]):
        xj = X[:, [j]]
        try:
            pred_lin = cross_val_predict(LinearRegression(), xj, y, cv=splits, n_jobs=-1)
            spline_model = make_pipeline(
                SplineTransformer(n_knots=4, degree=3, include_bias=False),
                StandardScaler(), Ridge(alpha=1.0)
            )
            pred_spl = cross_val_predict(spline_model, xj, y, cv=splits, n_jobs=-1)
            lr2 = r2_score(y, pred_lin); sr2 = r2_score(y, pred_spl)
        except Exception:
            lr2 = np.nan; sr2 = np.nan
        lin_r2s.append(lr2); spline_r2s.append(sr2); gains.append(sr2 - lr2)
    return np.asarray(lin_r2s), np.asarray(spline_r2s), np.asarray(gains)


def run_association(feature_df: pd.DataFrame, metadata_df: pd.DataFrame, target_col: str,
                    representation: str, split: str, bin_width=None,
                    transform="none", do_spline=False, do_nonlinear=True, seed=42):
    ids = feature_df.index.intersection(metadata_df.index)
    Xdf = feature_df.loc[ids].copy()
    yser = metadata_df.loc[ids, target_col]
    valid_rows = np.isfinite(yser.to_numpy(float)) & np.all(np.isfinite(Xdf.to_numpy(float)), axis=1)
    Xdf = Xdf.loc[valid_rows]
    yser = yser.loc[valid_rows]
    ids = Xdf.index
    if len(ids) < 12:
        raise ValueError(f"Only {len(ids)} usable samples")

    X = Xdf.to_numpy(float)
    if transform == "log1p":
        X = np.log1p(np.clip(X, 0, None))
    variances = np.nanvar(X, axis=0)
    keep = np.isfinite(variances) & (variances > 1e-18)
    X = X[:, keep]
    cols = Xdf.columns.to_numpy()[keep]
    if X.shape[1] == 0:
        raise ValueError("No non-constant features")
    y = yser.to_numpy(float)

    pearson = corr_columns(X, y)
    Xrank = np.apply_along_axis(rankdata, 0, X)
    yrank = rankdata(y)
    spearman = corr_columns(Xrank, yrank)
    pp = analytic_corr_p(pearson, len(y))
    sp = analytic_corr_p(spearman, len(y))
    _, pp_fdr, _, _ = multipletests(pp, alpha=FDR_ALPHA, method="fdr_bh")
    _, sp_fdr, _, _ = multipletests(sp, alpha=FDR_ALPHA, method="fdr_bh")

    pearson_perm, pearson_maxT = permutation_pvalues(X, y, pearson, N_PERMUTATIONS, seed, use_gpu=True)
    spearman_perm, spearman_maxT = permutation_pvalues(Xrank, yrank, spearman, N_PERMUTATIONS, seed + 1, use_gpu=True)
    p_lo, p_hi = bootstrap_correlation_ci(X, y, spearman=False, n_boot=N_BOOTSTRAP, seed=seed + 2)
    s_lo, s_hi = bootstrap_correlation_ci(X, y, spearman=True, n_boot=N_BOOTSTRAP, seed=seed + 3)

    # Nonlinear dependence scores are computed for the primary scientific
    # representations. Sensitivity-width and raw-area scans retain the much
    # faster Pearson/Spearman inference.
    if do_nonlinear:
        mi = mutual_info_regression(X, y, random_state=seed, n_neighbors=min(5, len(y) - 1))
        mi_counts = np.zeros(X.shape[1], dtype=int)
        mi_max = []
        rng = np.random.default_rng(seed + 4)
        for _ in range(N_MI_PERMUTATIONS):
            mip = mutual_info_regression(X, y[rng.permutation(len(y))], random_state=int(rng.integers(1, 2**31 - 1)), n_neighbors=min(5, len(y) - 1))
            mi_counts += mip >= mi
            mi_max.append(np.max(mip))
        mi_perm = (mi_counts + 1) / (N_MI_PERMUTATIONS + 1)
        mi_max = np.asarray(mi_max)
        mi_maxT = (np.sum(mi_max[:, None] >= mi[None, :], axis=0) + 1) / (N_MI_PERMUTATIONS + 1)
        dcor_vals = np.array([float(dcor.distance_correlation(X[:, j], y)) for j in range(X.shape[1])])
    else:
        mi = mi_perm = mi_maxT = dcor_vals = np.full(X.shape[1], np.nan)

    groups = metadata_df.loc[ids, "Reduced Composition"].fillna(metadata_df.loc[ids].index.to_series()).astype(str).to_numpy()
    if do_spline:
        lin_r2, spline_r2, spline_gain = spline_cv_gain(X, y, groups=groups)
    else:
        lin_r2 = spline_r2 = spline_gain = np.full(X.shape[1], np.nan)

    rows = []
    for j, col in enumerate(cols):
        lo, hi, center = parse_bin_from_feature(col)
        rows.append({
            "split": split, "representation": representation,
            "bin_width_THz": bin_width if bin_width is not None else np.nan,
            "feature": col, "bin_low_THz": lo, "bin_high_THz": hi, "bin_center_THz": center,
            "n": len(y), "transform": transform,
            "pearson_r": pearson[j], "pearson_ci95_low": p_lo[j], "pearson_ci95_high": p_hi[j],
            "pearson_p_analytic": pp[j], "pearson_p_fdr": pp_fdr[j],
            "pearson_p_permutation": pearson_perm[j], "pearson_p_maxT": pearson_maxT[j],
            "spearman_rho": spearman[j], "spearman_ci95_low": s_lo[j], "spearman_ci95_high": s_hi[j],
            "spearman_p_analytic": sp[j], "spearman_p_fdr": sp_fdr[j],
            "spearman_p_permutation": spearman_perm[j], "spearman_p_maxT": spearman_maxT[j],
            "mutual_information": mi[j], "mi_p_permutation": mi_perm[j], "mi_p_maxT": mi_maxT[j],
            "distance_correlation": dcor_vals[j],
            "linear_cv_R2": lin_r2[j], "spline_cv_R2": spline_r2[j],
            "nonlinear_spline_gain_R2": spline_gain[j],
        })
    return pd.DataFrame(rows), ids


def composition_static_features(meta_all: pd.DataFrame):
    compositions = {}
    element_set = set()
    for oid, formula in meta_all["Reduced Composition"].items():
        try:
            c = Composition(str(formula))
            compositions[oid] = c
            element_set.update(el.symbol for el in c.elements)
        except Exception:
            compositions[oid] = None
    elements = sorted(element_set, key=lambda s: Element(s).Z)
    rows = {}
    for oid, row in meta_all.iterrows():
        feats = {}
        c = compositions.get(oid)
        if c is not None:
            total = float(c.num_atoms)
            fracs = {el.symbol: float(c[el] / total) for el in c.elements}
            for el in elements:
                feats[f"frac_{el}"] = fracs.get(el, 0.0)
            props = defaultdict(list)
            weights = []
            for el in c.elements:
                e = Element(el.symbol)
                w = fracs[el.symbol]
                weights.append(w)
                props["Z"].append(float(e.Z))
                props["atomic_mass"].append(float(e.atomic_mass))
                props["X"].append(float(e.X) if e.X is not None else np.nan)
                props["row"].append(float(e.row) if e.row is not None else np.nan)
                props["group"].append(float(e.group) if e.group is not None else np.nan)
            weights = np.asarray(weights, float)
            for pname, vals in props.items():
                vals = np.asarray(vals, float)
                ok = np.isfinite(vals)
                if np.any(ok):
                    ww = weights[ok] / weights[ok].sum()
                    mean = np.sum(ww * vals[ok])
                    feats[f"comp_{pname}_mean"] = mean
                    feats[f"comp_{pname}_std"] = math.sqrt(max(np.sum(ww * (vals[ok] - mean) ** 2), 0))
                    feats[f"comp_{pname}_min"] = np.min(vals[ok])
                    feats[f"comp_{pname}_max"] = np.max(vals[ok])
        for col in ["Z", "Space group #", "a", "b", "c", "alpha", "beta", "gamma"]:
            feats[f"static_{col}"] = pd.to_numeric(row.get(col, np.nan), errors="coerce")
        rows[oid] = feats
    out = pd.DataFrame.from_dict(rows, orient="index").sort_index()
    out = out.dropna(axis=1, how="all")
    out.index.name = "ID"
    return out


def fit_crossfitted_residuals(X_train_df, X_test_df, train_meta, test_meta, static_df, target_col):
    train_ids = X_train_df.index.intersection(train_meta.index).intersection(static_df.index)
    test_ids = X_test_df.index.intersection(test_meta.index).intersection(static_df.index)
    train_ids = train_ids[np.isfinite(train_meta.loc[train_ids, target_col].to_numpy(float))]
    test_ids = test_ids[np.isfinite(test_meta.loc[test_ids, target_col].to_numpy(float))]
    common_cols = X_train_df.columns.intersection(X_test_df.columns)
    Xtr = X_train_df.loc[train_ids, common_cols].to_numpy(float)
    Xte = X_test_df.loc[test_ids, common_cols].to_numpy(float)
    Ztr = static_df.loc[train_ids].to_numpy(float)
    Zte = static_df.loc[test_ids].to_numpy(float)
    ytr = train_meta.loc[train_ids, target_col].to_numpy(float)
    yte = test_meta.loc[test_ids, target_col].to_numpy(float)
    groups = train_meta.loc[train_ids, "Reduced Composition"].fillna(pd.Series(train_ids, index=train_ids)).astype(str).to_numpy()
    splits = make_cv_splits(len(train_ids), groups=groups, n_splits=5)

    yhat = np.full(len(train_ids), np.nan)
    Xhat = np.full_like(Xtr, np.nan)
    for tr_idx, va_idx in splits:
        y_model = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(), Ridge(alpha=10.0))
        x_model = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(), Ridge(alpha=10.0))
        y_model.fit(Ztr[tr_idx], ytr[tr_idx]); yhat[va_idx] = y_model.predict(Ztr[va_idx])
        x_model.fit(Ztr[tr_idx], Xtr[tr_idx]); Xhat[va_idx] = x_model.predict(Ztr[va_idx])

    y_model = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(), Ridge(alpha=10.0))
    x_model = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(), Ridge(alpha=10.0))
    y_model.fit(Ztr, ytr); x_model.fit(Ztr, Xtr)
    yres_tr = ytr - yhat; Xres_tr = Xtr - Xhat
    yres_te = yte - y_model.predict(Zte); Xres_te = Xte - x_model.predict(Zte)

    train_res_df = pd.DataFrame(Xres_tr, index=train_ids, columns=common_cols)
    test_res_df = pd.DataFrame(Xres_te, index=test_ids, columns=common_cols)
    train_res_meta = train_meta.loc[train_ids].copy(); train_res_meta["residual_log10_ic"] = yres_tr
    test_res_meta = test_meta.loc[test_ids].copy(); test_res_meta["residual_log10_ic"] = yres_te
    return train_res_df, test_res_df, train_res_meta, test_res_meta


def regression_metrics(y_true, y_pred):
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": math.sqrt(mean_squared_error(y_true, y_pred)),
        "R2": r2_score(y_true, y_pred),
        "Spearman_rho": stats.spearmanr(y_true, y_pred).statistic,
    }


def evaluate_models(Xtr_df, Xte_df, train_meta, test_meta, target_col, cohort, feature_set, static_df=None):
    common_cols = Xtr_df.columns.intersection(Xte_df.columns)
    train_ids = Xtr_df.index.intersection(train_meta.index)
    test_ids = Xte_df.index.intersection(test_meta.index)
    train_ids = train_ids[np.isfinite(train_meta.loc[train_ids, target_col].to_numpy(float))]
    test_ids = test_ids[np.isfinite(test_meta.loc[test_ids, target_col].to_numpy(float))]
    Xtr = Xtr_df.loc[train_ids, common_cols].to_numpy(float)
    Xte = Xte_df.loc[test_ids, common_cols].to_numpy(float)
    ytr = train_meta.loc[train_ids, target_col].to_numpy(float)
    yte = test_meta.loc[test_ids, target_col].to_numpy(float)
    groups = train_meta.loc[train_ids, "Reduced Composition"].fillna(pd.Series(train_ids, index=train_ids)).astype(str).to_numpy()
    cv = make_cv_splits(len(train_ids), groups=groups, n_splits=5)

    results = []
    ridge = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scale", StandardScaler()),
        ("model", Ridge())
    ])
    search = GridSearchCV(ridge, {"model__alpha": np.logspace(-4, 4, 17)}, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)
    search.fit(Xtr, ytr)
    pred = search.predict(Xte)
    results.append({"cohort": cohort, "feature_set": feature_set, "model": "RidgeCV", "n_train": len(ytr), "n_test": len(yte), "best_params": json.dumps(search.best_params_), **regression_metrics(yte, pred)})

    if RUN_XGBOOST:
        try:
            from xgboost import XGBRegressor
            params = dict(
                n_estimators=600, max_depth=3, learning_rate=0.03,
                subsample=0.8, colsample_bytree=0.8,
                reg_lambda=5.0, reg_alpha=0.1,
                objective="reg:squarederror", random_state=RANDOM_SEED,
                tree_method="hist", n_jobs=-1,
            )
            if GPU_AVAILABLE:
                params["device"] = "cuda"
            model = Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("model", XGBRegressor(**params))
            ])
            model.fit(Xtr, ytr)
            pred = model.predict(Xte)
            results.append({"cohort": cohort, "feature_set": feature_set, "model": "XGBoost_GPU" if GPU_AVAILABLE else "XGBoost_CPU", "n_train": len(ytr), "n_test": len(yte), "best_params": json.dumps(params, default=str), **regression_metrics(yte, pred)})
        except Exception as exc:
            results.append({"cohort": cohort, "feature_set": feature_set, "model": "XGBoost_FAILED", "n_train": len(ytr), "n_test": len(yte), "best_params": str(exc), "MAE": np.nan, "RMSE": np.nan, "R2": np.nan, "Spearman_rho": np.nan})
    return results


def save_mean_spectrum_quartiles(feature_df, meta, target_col, title, outfile):
    ids = feature_df.index.intersection(meta.index)
    y = meta.loc[ids, target_col]
    valid = np.isfinite(y.to_numpy(float))
    ids = ids[valid]; y = y.loc[ids]
    if len(ids) < 20:
        return
    q = pd.qcut(y, 4, labels=["Q1: lowest σ", "Q2", "Q3", "Q4: highest σ"], duplicates="drop")
    centers = np.array([parse_bin_from_feature(c)[2] for c in feature_df.columns])
    plt.figure(figsize=(8.2, 5.2))
    for label in q.cat.categories:
        selected = q.index[q == label]
        mean = feature_df.loc[selected].mean(axis=0).to_numpy(float)
        sem = feature_df.loc[selected].sem(axis=0).to_numpy(float)
        plt.plot(centers, mean, label=f"{label} (n={len(selected)})")
        plt.fill_between(centers, mean - sem, mean + sem, alpha=0.15)
    plt.xlabel("Frequency (THz)"); plt.ylabel("Normalized spectral weight per bin")
    plt.title(title); plt.legend(frameon=False, fontsize=8); plt.tight_layout()
    plt.savefig(outfile, dpi=300); plt.close()


def save_association_curve(train_assoc, test_assoc, representation, outfile):
    tr = train_assoc.sort_values("bin_center_THz")
    te = test_assoc.sort_values("bin_center_THz")
    plt.figure(figsize=(8.4, 5.2))
    plt.axhline(0, linewidth=1)
    plt.plot(tr["bin_center_THz"], tr["spearman_rho"], label="Train discovery")
    plt.fill_between(tr["bin_center_THz"], tr["spearman_ci95_low"], tr["spearman_ci95_high"], alpha=0.18)
    plt.plot(te["bin_center_THz"], te["spearman_rho"], linestyle="--", label="Test replication")
    sig = tr["spearman_p_maxT"] < 0.05
    if sig.any():
        plt.scatter(tr.loc[sig, "bin_center_THz"], tr.loc[sig, "spearman_rho"], marker="o", s=22, label="Train maxT p<0.05")
    plt.xlabel("Frequency-bin center (THz)"); plt.ylabel("Spearman ρ with log$_{10}$ conductivity")
    plt.title(representation.replace("_", " ")); plt.legend(frameon=False); plt.tight_layout()
    plt.savefig(outfile, dpi=300); plt.close()


def save_replication_scatter(replication_df, outfile):
    if replication_df.empty:
        return
    plt.figure(figsize=(6.2, 5.6))
    for rep, grp in replication_df.groupby("representation"):
        plt.scatter(grp["spearman_rho_train"], grp["spearman_rho_test"], s=22, alpha=0.75, label=rep)
    lim = np.nanmax(np.abs(replication_df[["spearman_rho_train", "spearman_rho_test"]].to_numpy()))
    lim = max(lim, 0.1)
    plt.plot([-lim, lim], [-lim, lim], linestyle=":")
    plt.axhline(0, linewidth=0.8); plt.axvline(0, linewidth=0.8)
    plt.xlim(-lim * 1.05, lim * 1.05); plt.ylim(-lim * 1.05, lim * 1.05)
    plt.xlabel("Train Spearman ρ"); plt.ylabel("Test Spearman ρ")
    plt.title("Frequency-bin effect replication")
    plt.legend(frameon=False, fontsize=8); plt.tight_layout(); plt.savefig(outfile, dpi=300); plt.close()


def save_model_plot(model_df, outfile):
    if model_df.empty:
        return
    d = model_df.dropna(subset=["MAE"]).copy()
    if d.empty:
        return
    labels = d["cohort"] + "\n" + d["feature_set"] + "\n" + d["model"]
    x = np.arange(len(d))
    plt.figure(figsize=(max(9, 0.48 * len(d)), 5.7))
    plt.bar(x, d["MAE"])
    plt.xticks(x, labels, rotation=75, ha="right", fontsize=7)
    plt.ylabel("Held-out test MAE in log$_{10}$(S cm$^{-1}$)")
    plt.title("Predictive confirmation on the official OBELiX test split")
    plt.tight_layout(); plt.savefig(outfile, dpi=300); plt.close()

# ------------------------------ DOWNLOAD -------------------------------
# ----------------------- VERIFY MOUNTED FOLDERS ------------------------
print("\nVerifying mounted Drive folders...")

for (split, mode), (_, root) in FOLDER_SPECS.items():
    if not root.exists():
        raise FileNotFoundError(
            f"Mounted folder does not exist for {split}/{mode}: {root}"
        )

    file_count = sum(1 for p in root.rglob("*") if p.is_file())

    if file_count == 0:
        raise RuntimeError(
            f"No files were found for {split}/{mode} in:\n{root}"
        )

    print(
        f"  {split.upper():5s} {mode.upper():4s}: "
        f"{file_count:,} files in {root}"
    )

print("Mounted folders verified. No Drive files will be downloaded or copied.")

# Official OBELiX tables
TRAIN_CSV = "https://raw.githubusercontent.com/NRC-Mila/OBELiX/main/data/downloads/train.csv"
TEST_CSV  = "https://raw.githubusercontent.com/NRC-Mila/OBELiX/main/data/downloads/test.csv"
train_meta = prepare_obelix(pd.read_csv(TRAIN_CSV, dtype={"ID": str}), "train").set_index("ID", drop=False)
test_meta  = prepare_obelix(pd.read_csv(TEST_CSV, dtype={"ID": str}), "test").set_index("ID", drop=False)
meta_all = pd.concat([train_meta, test_meta], axis=0)
known_ids = set(meta_all.index)
TARGET = target_column(PRIMARY_CENSOR_POLICY)
print(f"OBELiX rows: train={len(train_meta)}, test={len(test_meta)}; primary target={TARGET}")

# ---------------------------- PARSE SPECTRA ----------------------------
collections = {}
qc_frames, index_frames, unmatched_frames = [], [], []
for (split, mode), (_, root) in FOLDER_SPECS.items():
    spectra, qc, idx, unmatched = load_collection(root, split, mode, known_ids)
    collections[(split, mode)] = spectra
    qc_frames.append(qc)
    if not idx.empty:
        idx["split"] = split; index_frames.append(idx)
    if not unmatched.empty:
        unmatched["split"] = split; unmatched_frames.append(unmatched)

qc_all = pd.concat(qc_frames, ignore_index=True) if qc_frames else pd.DataFrame()
file_index = pd.concat(index_frames, ignore_index=True) if index_frames else pd.DataFrame()
unmatched_files = pd.concat(unmatched_frames, ignore_index=True) if unmatched_frames else pd.DataFrame()
qc_all.to_csv(TABLES / "spectrum_QC_all.csv", index=False)
# ---------------- VERIFY THAT LI-PDOS WAS READ CORRECTLY ----------------
pdos_qc = qc_all[
    (qc_all["mode"] == "pdos")
    & (qc_all["status"] == "ok")
].copy()

if pdos_qc.empty:
    raise RuntimeError("No Li-PDOS spectra were parsed successfully.")

unsafe_pdos = pdos_qc[
    ~pdos_qc["parse_mode"].astype(str).isin([
        "named_column_Li_PDOS",
        "summed_named_Li_PDOS_columns",
        "Li_columns_from_atom_resolved_PDOS",
        "Li_columns_from_xyz_resolved_PDOS",
        "single_Li_PDOS_column",
    ])
]

print("\nLi-PDOS parser modes:")
print(
    pdos_qc["parse_mode"]
    .value_counts(dropna=False)
    .to_string()
)

if len(unsafe_pdos):
    unsafe_pdos.to_csv(
        TABLES / "UNSAFE_OR_UNVERIFIED_PDOS_FILES.csv",
        index=False
    )

    raise RuntimeError(
        f"{len(unsafe_pdos)} PDOS files were not parsed using verified "
        "Li-specific columns. Inspect "
        "tables/UNSAFE_OR_UNVERIFIED_PDOS_FILES.csv."
    )

print(
    "\nAll successfully parsed PDOS spectra use explicitly identified "
    "Li-specific columns."
)
file_index.to_csv(TABLES / "spectrum_file_candidates_and_selection.csv", index=False)
unmatched_files.to_csv(TABLES / "unmatched_spectrum_files.csv", index=False)

# Fallback warning is intentionally conspicuous.
if not qc_all.empty and "parse_mode" in qc_all:
    fallback = qc_all[qc_all["parse_mode"].astype(str).str.contains("FALLBACK", na=False)]
    if len(fallback):
        print("\nWARNING: metadata-free multi-column PDOS files were summed as Li-PDOS.")
        print(f"Affected structures: {len(fallback)}. Inspect tables/spectrum_QC_all.csv before publication.")

coverage_rows = []
for split in ["train", "test"]:
    dos_ids = set(collections[(split, "dos")])
    pdos_ids = set(collections[(split, "pdos")])
    target_ids = set((train_meta if split == "train" else test_meta).dropna(subset=[TARGET]).index)
    coverage_rows.append({
        "split": split, "OBELiX_rows": len(train_meta if split == "train" else test_meta),
        "valid_target_rows": len(target_ids), "parsed_DOS": len(dos_ids), "parsed_Li_PDOS": len(pdos_ids),
        "paired_DOS_and_PDOS": len(dos_ids & pdos_ids),
        "DOS_with_target": len(dos_ids & target_ids), "PDOS_with_target": len(pdos_ids & target_ids),
        "paired_with_target": len(dos_ids & pdos_ids & target_ids),
    })
coverage_df = pd.DataFrame(coverage_rows)
coverage_df.to_csv(TABLES / "dataset_coverage.csv", index=False)
print("\nCoverage:\n", coverage_df.to_string(index=False))

# ------------------------- FEATURES AND DESCRIPTORS --------------------
feature_store = defaultdict(dict)   # (split, width) -> named DataFrames
edges_store = {}
for split in ["train", "test"]:
    for width in BIN_WIDTHS_THz:
        dos_area, dos_shape, edges = collection_to_features(collections[(split, "dos")], "totalDOS", width)
        li_area, li_shape, _ = collection_to_features(collections[(split, "pdos")], "LiPDOS", width)
        feature_store[(split, width)]["total_area"] = dos_area
        feature_store[(split, width)]["total_shape"] = dos_shape
        feature_store[(split, width)]["li_area"] = li_area
        feature_store[(split, width)]["li_shape"] = li_shape
        edges_store[width] = edges

        # Paired Li participation and host-DOS features are created only when
        # the PDOS and total DOS normalizations appear compatible.
        paired_ids = dos_area.index.intersection(li_area.index)
        if len(paired_ids):
            totalA = dos_area.loc[paired_ids].to_numpy(float)
            liA = li_area.loc[paired_ids].to_numpy(float)
            ratio = liA.sum(1) / np.maximum(totalA.sum(1), 1e-15)
            compatible = np.isfinite(ratio) & (ratio >= 0) & (ratio <= 1.25)
            compatibility_rate = float(np.mean(compatible))
            comp_rows = pd.DataFrame({"ID": paired_ids, "split": split, "bin_width_THz": width, "Li_area_over_total_area": ratio, "normalization_compatible": compatible})
            comp_rows.to_csv(TABLES / f"{split}_PDOS_DOS_normalization_check_{width:g}THz.csv", index=False)
            if compatibility_rate >= 0.80 and np.sum(compatible) >= 12:
                ids_ok = paired_ids[compatible]
                total_ok = dos_area.loc[ids_ok].copy()
                li_ok = li_area.loc[ids_ok].copy()
                # Rename columns to a common grid before arithmetic.
                common_names = [f"paired_{edges[i]:06.2f}_{edges[i+1]:06.2f}THz" for i in range(len(edges)-1)]
                total_ok.columns = common_names; li_ok.columns = common_names
                host = (total_ok - li_ok).clip(lower=0)
                host_shape = host.div(host.sum(axis=1).replace(0, np.nan), axis=0)
                participation = li_ok / (total_ok + 1e-15)
                feature_store[(split, width)]["host_shape"] = host_shape
                feature_store[(split, width)]["li_participation"] = participation

        for name, df in feature_store[(split, width)].items():
            df.reset_index().to_csv(FEATURES_DIR / f"{split}_{name}_{width:g}THz.csv", index=False)

# Compact interpretable descriptors
desc_train = pd.concat([
    descriptors_table(collections[("train", "dos")], "totalDOS"),
    descriptors_table(collections[("train", "pdos")], "LiPDOS")
], axis=1)
desc_test = pd.concat([
    descriptors_table(collections[("test", "dos")], "totalDOS"),
    descriptors_table(collections[("test", "pdos")], "LiPDOS")
], axis=1)
desc_train.reset_index().to_csv(FEATURES_DIR / "train_compact_spectral_descriptors.csv", index=False)
desc_test.reset_index().to_csv(FEATURES_DIR / "test_compact_spectral_descriptors.csv", index=False)

# ------------------------- ASSOCIATION ANALYSIS ------------------------
association_frames = []
for width in BIN_WIDTHS_THz:
    for representation in ["total_shape", "li_shape", "total_area", "li_area", "host_shape", "li_participation"]:
        for split, meta in [("train", train_meta), ("test", test_meta)]:
            df = feature_store[(split, width)].get(representation)
            if df is None or df.empty:
                continue
            transform = "log1p" if representation.endswith("_area") else "none"
            do_spline = bool(
                RUN_SPLINE_NONLINEARITY and split == "train"
                and abs(width - PRIMARY_BIN_WIDTH_THz) < 1e-9
                and representation in {"total_shape", "li_shape"}
            )
            do_nonlinear = bool(
                abs(width - PRIMARY_BIN_WIDTH_THz) < 1e-9
                and representation in {"total_shape", "li_shape", "host_shape", "li_participation"}
            )
            try:
                assoc, used_ids = run_association(
                    df, meta, TARGET, representation, split,
                    bin_width=width, transform=transform, do_spline=do_spline,
                    do_nonlinear=do_nonlinear,
                    seed=RANDOM_SEED + int(round(width * 100)) + (0 if split == "train" else 10000)
                )
                association_frames.append(assoc)
                assoc.to_csv(ASSOC_DIR / f"{split}_{representation}_{width:g}THz_associations.csv", index=False)
                print(f"Association completed: {split} / {representation} / {width:g} THz / n={len(used_ids)}")
            except Exception as exc:
                print(f"WARNING association skipped: {split} / {representation} / {width:g} THz: {exc}")

# Descriptor associations
for split, df, meta in [("train", desc_train, train_meta), ("test", desc_test, test_meta)]:
    try:
        assoc, _ = run_association(df, meta, TARGET, "compact_descriptors", split, bin_width=None, transform="none", do_spline=(RUN_SPLINE_NONLINEARITY and split == "train"), do_nonlinear=True, seed=RANDOM_SEED + (20000 if split == "test" else 15000))
        association_frames.append(assoc)
        assoc.to_csv(ASSOC_DIR / f"{split}_compact_descriptor_associations.csv", index=False)
    except Exception as exc:
        print(f"WARNING descriptor association skipped for {split}: {exc}")

all_assoc = pd.concat(association_frames, ignore_index=True) if association_frames else pd.DataFrame()
all_assoc.to_csv(TABLES / "all_association_results.csv", index=False)

# Train-to-test replication table for exactly matching features.
replication_rows = []
if not all_assoc.empty:
    for (rep, width), grp in all_assoc.groupby(["representation", "bin_width_THz"], dropna=False):
        tr = grp[grp["split"] == "train"]
        te = grp[grp["split"] == "test"]
        if tr.empty or te.empty:
            continue
        merged = tr.merge(te, on="feature", suffixes=("_train", "_test"))
        for _, r in merged.iterrows():
            replication_rows.append({
                "representation": rep, "bin_width_THz": width, "feature": r["feature"],
                "bin_center_THz": r.get("bin_center_THz_train", np.nan),
                "spearman_rho_train": r["spearman_rho_train"], "spearman_rho_test": r["spearman_rho_test"],
                "pearson_r_train": r["pearson_r_train"], "pearson_r_test": r["pearson_r_test"],
                "same_sign_spearman": np.sign(r["spearman_rho_train"]) == np.sign(r["spearman_rho_test"]),
                "train_spearman_p_maxT": r["spearman_p_maxT_train"], "test_spearman_p_analytic": r["spearman_p_analytic_test"],
            })
replication_df = pd.DataFrame(replication_rows)
replication_df.to_csv(TABLES / "train_test_effect_replication.csv", index=False)

# ---------------- CENSORING SENSITIVITY (FAST SPEARMAN SCAN) -----------
def censor_sensitivity_scan(df, meta, representation, split):
    out = []
    for policy in ["limit", "half_limit", "exclude"]:
        tcol = target_column(policy)
        ids = df.index.intersection(meta.index)
        y = meta.loc[ids, tcol]
        good = np.isfinite(y.to_numpy(float)) & np.all(np.isfinite(df.loc[ids].to_numpy(float)), axis=1)
        X = df.loc[ids[good]].to_numpy(float); yy = y.loc[ids[good]].to_numpy(float)
        keep = np.nanvar(X, axis=0) > 1e-18
        X = X[:, keep]; cols = df.columns.to_numpy()[keep]
        if len(yy) < 12 or X.shape[1] == 0:
            continue
        rho = corr_columns(np.apply_along_axis(rankdata, 0, X), rankdata(yy))
        for c, r in zip(cols, rho):
            lo, hi, center = parse_bin_from_feature(c)
            out.append({"split": split, "representation": representation, "censor_policy": policy, "feature": c, "bin_center_THz": center, "n": len(yy), "spearman_rho": r})
    return out

censor_rows = []
for split, meta in [("train", train_meta), ("test", test_meta)]:
    for rep in ["total_shape", "li_shape"]:
        df = feature_store[(split, PRIMARY_BIN_WIDTH_THz)].get(rep)
        if df is not None:
            censor_rows.extend(censor_sensitivity_scan(df, meta, rep, split))
pd.DataFrame(censor_rows).to_csv(TABLES / "censoring_policy_sensitivity.csv", index=False)

# ---------------------- CONDITIONAL ASSOCIATIONS -----------------------
static_features = composition_static_features(meta_all)
static_features.reset_index().to_csv(FEATURES_DIR / "composition_and_static_confounders.csv", index=False)
conditional_frames = []
if RUN_CONDITIONAL_ASSOCIATIONS:
    for rep in ["total_shape", "li_shape"]:
        Xtr = feature_store[("train", PRIMARY_BIN_WIDTH_THz)].get(rep)
        Xte = feature_store[("test", PRIMARY_BIN_WIDTH_THz)].get(rep)
        if Xtr is None or Xte is None:
            continue
        try:
            tr_res, te_res, tr_meta_res, te_meta_res = fit_crossfitted_residuals(Xtr, Xte, train_meta, test_meta, static_features, TARGET)
            for split, Xres, Mres in [("train", tr_res, tr_meta_res), ("test", te_res, te_meta_res)]:
                assoc, _ = run_association(
                    Xres, Mres, "residual_log10_ic", f"conditional_{rep}", split,
                    bin_width=PRIMARY_BIN_WIDTH_THz, transform="none",
                    do_spline=(RUN_SPLINE_NONLINEARITY and split == "train"),
                    do_nonlinear=True,
                    seed=RANDOM_SEED + (31000 if split == "train" else 32000)
                )
                conditional_frames.append(assoc)
                assoc.to_csv(ASSOC_DIR / f"{split}_conditional_{rep}_associations.csv", index=False)
        except Exception as exc:
            print(f"WARNING conditional association skipped for {rep}: {exc}")
conditional_assoc = pd.concat(conditional_frames, ignore_index=True) if conditional_frames else pd.DataFrame()
conditional_assoc.to_csv(TABLES / "conditional_residual_associations.csv", index=False)

# --------------------------- PREDICTIVE CHECK --------------------------
model_rows = []
if RUN_PREDICTIVE_MODELS:
    # Cohort-specific comparisons ensure every static-vs-spectral comparison
    # uses exactly the same materials.
    cases = []
    for cohort, rep_names in [("DOS cohort", ["total_shape"]), ("Li-PDOS cohort", ["li_shape"]), ("paired cohort", ["total_shape", "li_shape"])]:
        tr_dfs = [feature_store[("train", PRIMARY_BIN_WIDTH_THz)].get(r) for r in rep_names]
        te_dfs = [feature_store[("test", PRIMARY_BIN_WIDTH_THz)].get(r) for r in rep_names]
        if any(x is None for x in tr_dfs + te_dfs):
            continue
        tr_ids = tr_dfs[0].index
        te_ids = te_dfs[0].index
        for d in tr_dfs[1:]: tr_ids = tr_ids.intersection(d.index)
        for d in te_dfs[1:]: te_ids = te_ids.intersection(d.index)
        spec_tr = pd.concat([d.loc[tr_ids] for d in tr_dfs], axis=1)
        spec_te = pd.concat([d.loc[te_ids] for d in te_dfs], axis=1)
        stat_tr = static_features.loc[tr_ids]
        stat_te = static_features.loc[te_ids]
        combo_tr = pd.concat([stat_tr, spec_tr], axis=1)
        combo_te = pd.concat([stat_te, spec_te], axis=1)
        cases.extend([
            (cohort, "static only", stat_tr, stat_te),
            (cohort, "+".join(rep_names), spec_tr, spec_te),
            (cohort, "static + " + "+".join(rep_names), combo_tr, combo_te),
        ])
    for cohort, fset, Xtr, Xte in cases:
        try:
            model_rows.extend(evaluate_models(Xtr, Xte, train_meta, test_meta, TARGET, cohort, fset))
            print(f"Models completed: {cohort} / {fset}")
        except Exception as exc:
            print(f"WARNING models skipped: {cohort} / {fset}: {exc}")
model_df = pd.DataFrame(model_rows)
model_df.to_csv(TABLES / "heldout_predictive_model_performance.csv", index=False)

# ------------------------------- FIGURES -------------------------------
# Dataset coverage
plt.figure(figsize=(7.2, 4.8))
x = np.arange(len(coverage_df)); w = 0.25
plt.bar(x - w, coverage_df["DOS_with_target"], width=w, label="Total DOS")
plt.bar(x, coverage_df["PDOS_with_target"], width=w, label="Li-PDOS")
plt.bar(x + w, coverage_df["paired_with_target"], width=w, label="Paired")
plt.xticks(x, coverage_df["split"].str.capitalize()); plt.ylabel("Materials with conductivity target")
plt.title("Spectral dataset coverage"); plt.legend(frameon=False); plt.tight_layout()
plt.savefig(FIGURES / "01_dataset_coverage.png", dpi=300); plt.close()

save_mean_spectrum_quartiles(feature_store[("train", PRIMARY_BIN_WIDTH_THz)]["total_shape"], train_meta, TARGET,
                              "Train total DOS by conductivity quartile", FIGURES / "02_total_DOS_by_conductivity_quartile.png")
save_mean_spectrum_quartiles(feature_store[("train", PRIMARY_BIN_WIDTH_THz)]["li_shape"], train_meta, TARGET,
                              "Train Li-projected DOS by conductivity quartile", FIGURES / "03_Li_PDOS_by_conductivity_quartile.png")

if not all_assoc.empty:
    for rep, num in [("total_shape", "04"), ("li_shape", "05")]:
        tr = all_assoc[(all_assoc["split"] == "train") & (all_assoc["representation"] == rep) & (all_assoc["bin_width_THz"] == PRIMARY_BIN_WIDTH_THz)]
        te = all_assoc[(all_assoc["split"] == "test") & (all_assoc["representation"] == rep) & (all_assoc["bin_width_THz"] == PRIMARY_BIN_WIDTH_THz)]
        if not tr.empty and not te.empty:
            save_association_curve(tr, te, rep, FIGURES / f"{num}_{rep}_frequency_associations.png")

rep_primary = replication_df[replication_df["bin_width_THz"] == PRIMARY_BIN_WIDTH_THz] if not replication_df.empty else pd.DataFrame()
save_replication_scatter(rep_primary, FIGURES / "06_train_test_effect_replication.png")
save_model_plot(model_df, FIGURES / "07_predictive_model_MAE.png")

# Top compact descriptors
if not all_assoc.empty:
    d = all_assoc[(all_assoc["split"] == "train") & (all_assoc["representation"] == "compact_descriptors")].copy()
    if not d.empty:
        d = d.reindex(d["spearman_rho"].abs().sort_values(ascending=False).index).head(15).sort_values("spearman_rho")
        plt.figure(figsize=(8.2, 6.2)); plt.barh(d["feature"], d["spearman_rho"])
        plt.xlabel("Train Spearman ρ with log$_{10}$ conductivity"); plt.title("Top compact spectral descriptors")
        plt.tight_layout(); plt.savefig(FIGURES / "08_top_compact_descriptor_associations.png", dpi=300); plt.close()

# ----------------------------- TEXT SUMMARY ----------------------------
summary_lines = []
summary_lines.append("OBELiX DOS / Li-PDOS ASSOCIATION WORKFLOW")
summary_lines.append("=" * 52)
summary_lines.append(f"Device: {DEVICE_NAME}")
summary_lines.append(f"Frequency inclusion: 0 < frequency <= {FREQ_MAX_THz} THz")
summary_lines.append("Negative-frequency structures were NOT removed; only non-positive frequency points were excluded from features.")
summary_lines.append(f"Primary bin width: {PRIMARY_BIN_WIDTH_THz} THz; sensitivity widths: {BIN_WIDTHS_THz}")
summary_lines.append(f"Primary target: {TARGET}")
summary_lines.append("")
summary_lines.append("Coverage:")
summary_lines.append(coverage_df.to_string(index=False))

if not all_assoc.empty:
    for rep in ["total_shape", "li_shape", "compact_descriptors"]:
        d = all_assoc[(all_assoc["split"] == "train") & (all_assoc["representation"] == rep)]
        if rep != "compact_descriptors":
            d = d[d["bin_width_THz"] == PRIMARY_BIN_WIDTH_THz]
        if not d.empty:
            top = d.reindex(d["spearman_rho"].abs().sort_values(ascending=False).index).head(10)
            summary_lines.append(f"\nTop train effects: {rep}")
            summary_lines.append(top[["feature", "n", "spearman_rho", "spearman_ci95_low", "spearman_ci95_high", "spearman_p_fdr", "spearman_p_maxT", "distance_correlation", "mutual_information", "nonlinear_spline_gain_R2"]].to_string(index=False))

if not model_df.empty:
    summary_lines.append("\nHeld-out model performance:")
    summary_lines.append(model_df[["cohort", "feature_set", "model", "n_train", "n_test", "MAE", "RMSE", "R2", "Spearman_rho"]].to_string(index=False))

summary_text = "\n".join(summary_lines)
(RESULTS / "SUMMARY.txt").write_text(summary_text)
print("\n" + summary_text)

config = {
    "mounted_drive_folders": {
    f"{s}_{m}": str(root)
    for (s, m), (_, root) in FOLDER_SPECS.items()
},
    "frequency_range_THz": [FREQ_MIN_THz, FREQ_MAX_THz],
    "frequency_scale_to_THz": FREQUENCY_SCALE_TO_THz,
    "bin_widths_THz": BIN_WIDTHS_THz,
    "primary_bin_width_THz": PRIMARY_BIN_WIDTH_THz,
    "primary_censor_policy": PRIMARY_CENSOR_POLICY,
    "n_bootstrap": N_BOOTSTRAP,
    "n_permutations": N_PERMUTATIONS,
    "n_mi_permutations": N_MI_PERMUTATIONS,
    "random_seed": RANDOM_SEED,
    "device": DEVICE_NAME,
    "pdos_multicolumn_fallback": PDOS_MULTICOLUMN_FALLBACK,
}
(RESULTS / "run_config.json").write_text(json.dumps(config, indent=2))

# ------------------------------- ARCHIVE -------------------------------
zip_path = Path("/content/OBELiX_DOS_PDOS_association_outputs.zip")
if zip_path.exists(): zip_path.unlink()
shutil.make_archive(str(zip_path.with_suffix("")), "zip", root_dir=RESULTS)
print(f"\nFinished. Output archive: {zip_path}")
from google.colab import files
files.download(str(zip_path))


if AUTO_DOWNLOAD_ZIP:
    try:
        from google.colab import files
        files.download(str(zip_path))
    except Exception as exc:
        print(f"Automatic browser download was not started: {exc}")